version: "3"

services:
  service1:
    build:
      context: ./service1
      dockerfile: dev.Dockerfile
    container_name: service1
    ports:
      - 8199:8199
    networks:
      - service_network
    volumes:
      - type: bind
        source: ./vStorage
        target: /usr/src/vStorage
    environment:
      - PORT=8199
      - S2_URL=service2
      - S2_PORT=9191
      - STORAGE_URL=storage
      - STORAGE_PORT=8080

  service2:
    build:
      context: ./service2
      dockerfile: dev.Dockerfile
    container_name: service2
    networks:
      - service_network
    volumes:
      - type: bind
        source: ./vStorage
        target: /usr/src/vStorage
    environment:
      - PORT=9191
      - STORAGE_URL=storage
      - STORAGE_PORT=8080

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    container_name: storage
    networks:
      - service_network
    volumes:
      - storage-volume:/data
    environment:
      - PORT=8080

networks:
  service_network:
    driver: bridge

volumes:
  storage-volume:
