version: "3"

services:
  service1:
    build:
      context: ./service1
      dockerfile: dev.Dockerfile
    container_name: service1
    ports:
      - 8199:8199
    networks:
      - service_network
  
  service2:
    build:
      context: ./service2
      dockerfile: dev.Dockerfile
    container_name: service2
    networks:
      - service_network
